### ISSUE TITLE
Mobile app access through a basic auth reverse proxy

### ISSUE THREAD

**Issue by callahan22** [tidusjar/Ombi#3102]
**Describe the bug**
I am unable to access Ombi using the mobile app on Android through a reverse proxy server with basic auth

**To Reproduce**
1. Punch in the URL on the mobile app of the site you've set up on the reverse proxy server.
2. Fails to resolve.

**Expected behavior**
I expect exactly this behaviour. The basic auth is preventing access I expect. I have tried it without basic auth however and it still fails to work on the internal network. Not entirely sure why.
I was wondering if the mobile app version of the site is served from a different location so I could try adding a server block without authentication that serves requests for /mobile (or whatever it happens to be). On that same point, if this is possible, I'm essentially bypoassing the basic auth protection so kind of defeating the purpose! So I guess I should be asking if there are any plans to add tokens or allow URLs like username:password@myombi.mywebsite.com?

**Docker config:**
```
ombi:
    image: linuxserver/ombi
    container_name: ombi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/ombi/config:/config
      - ./docker/shared:/shared
    ports:
      - "8005:3579"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=999
      - TZ=Europe/London
```
**NGINX config:**
```
server {

  listen 80;
  listen [::]:80;
  server_name ombi.mywebsite.com;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  server_name ombi.mywebsite.com;
  client_max_body_size 0;
  underscores_in_headers on;
  auth_basic "$site_authentication";
  auth_basic_user_file /etc/nginx/.passwd;
  # Cookie lifetime = 10 minutes
  add_header Set-Cookie "access=67916062;max-age=600;path=/"; #Set the "access" cookie when user has logged in

  location / {
    proxy_headers_hash_max_size 512;
    proxy_headers_hash_bucket_size 64;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    add_header Front-End-Https on;
    proxy_pass http://192.168.1.7:8005;
    proxy_read_timeout 90;
  }
```
