### ISSUE TITLE
Custom CSS not applied when logging out.

### ISSUE THREAD

**Issue by phillipjf** [tidusjar/Ombi#3486]
**Describe the bug**
When logging out, custom CSS is not applied to the login page shown to the user.

**To Reproduce**
1. Apply Custom CSS:
```css
#profile-img { display: none; }

div.ng-tns-c1-0>div.form-signin:nth-of-type(1) {
  margin-bottom: -96px;
}

div.ng-tns-c1-0>div.form-signin:nth-of-type(1)>button {
  font-size: 0px;
  background-color: transparent;
}

div.ng-tns-c1-0>div.form-signin:nth-of-type(1)>button::after {
  font-size: 15px;
  font-weight: 400;
  content: "Admin";
}

div.ng-tns-c1-0>div.form-signin:nth-of-type(2)>button {
  font-size: 0px;
}

div.ng-tns-c1-0>div.form-signin:nth-of-type(2)>button::after {
  font-size: 15px;
}
div.ng-tns-c1-0>div.form-signin:nth-of-type(2)>button::after {
  content: "Sign In";
}
```
2. Load login screen. See custom CSS applied.
![rendered](https://user-images.githubusercontent.com/8834707/79073945-0e582480-7caf-11ea-86d9-5b3f8b9c08d2.png)
3. Login
4. Logout. See custom CSS not rendered.
![not-rendered](https://user-images.githubusercontent.com/8834707/79073946-0e582480-7caf-11ea-9847-dbcda8344e5c.png)

**Expected behavior**
The custom CSS renders.

**Screenshots**
See screenshots in-line with step to reproduce.

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Browser (Firefox v74.0)

**Ombi Version (please complete the following information):**
 - Version: 3.0.4892
