### ISSUE TITLE
v4 Discover page hang

### ISSUE THREAD

**Issue by gipasoft** [tidusjar/Ombi#3674]
**Describe the bug**
When I go to Discover page the page hang

**To Reproduce**
1. Go to 'Discover page'
2. See error
```
http://192.168.1.131:8978/api/v2/search/Tv/popular/0/14: 500 Internal Server Error","error":{"error":"The remote certificate is invalid according to the validation procedure."}}
    at k (polyfills.330e93a5e634aa70f222.js:1)
    at polyfills.330e93a5e634aa70f222.js:1
    at a (16.3aa2c6f09d25b79a4424.js:1)
    at e.invoke (polyfills.330e93a5e634aa70f222.js:1)
    at Object.onInvoke (main.ccb6273d249a85e7a3fd.js:1)
    at e.invoke (polyfills.330e93a5e634aa70f222.js:1)
    at t.run (polyfills.330e93a5e634aa70f222.js:1)
    at polyfills.330e93a5e634aa70f222.js:1
    at e.invokeTask (polyfills.330e93a5e634aa70f222.js:1)
    at Object.onInvokeTask (main.ccb6273d249a85e7a3fd.js:1) 
```

**Expected behavior**
View the Discover page

**Screenshots**
![image](https://user-images.githubusercontent.com/1884550/87676742-41f88e00-c779-11ea-8675-dfc11af1ac17.png)

**Logs (Logs directory where Ombi is located)**
[logs.zip](https://github.com/tidusjar/Ombi/files/4931785/logs.zip)

**Desktop (please complete the following information):**
 - OS: Qnap TS-653B - Firmware: 4.4.3.1354

**Ombi Version (please complete the following information):**
 - Version 4.0.407
- Media Server Plex media server (1.19.4)

**Additional context**

**Comment by tidusjar** [comment]
Is this the qnap pkg or docker?

**Comment by gipasoft** [comment]
> Is this the qnap pkg or docker?

Is the qnap qpkg

**Comment by tidusjar** [comment]
Apologies but I have no dealings with the QNAP pkgs due to the awful attitude of the maintainers of that pkg. I would really advise you to attempt to get your money back and then use the free docker version provided by LSIO. 

Regarding the issue, might be a temp issue at the API provider or something within the pkg itself. I have never seen this issue before and it is working fine for myself. 

Again, please move off that package, it will not be supported going forward

**Comment by gipasoft** [comment]
Thank for your reply ... where can i find a docker version with ombi v4 installed?

**Comment by gipasoft** [comment]
Excuse but I am very dummy in docker ... I've installed Ombi with this script:
```
version: "2.1"
services:
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - BASE_URL=/ombi #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
```
but so I've installed version 3 of Ombi, how cain install the version 4?

**Comment by didyouexpectthat** [comment]
@gipasoft use `image: linuxserver/ombi:v4-preview`

**Comment by didyouexpectthat** [comment]
Other tags are available from: https://hub.docker.com/r/linuxserver/ombi/tags/

**Comment by gipasoft** [comment]
I have installed the v4 preview with dock container, with this script:
```
version: "2.1"
services:
  ombi:
    image: linuxserver/ombi:v4-preview
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - BASE_URL=/ombi #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped

```
I have started the container but the default page hang:
![image](https://user-images.githubusercontent.com/1884550/87764574-eed51880-c816-11ea-9479-e248779f936f.png)

This are the logs:
ombi: 
[log-20200717.txt](https://github.com/tidusjar/Ombi/files/4936593/log-20200717.txt)
container:
[container-station-log.zip](https://github.com/tidusjar/Ombi/files/4936599/container-station-log.zip)
